"""
Django settings for argus_transaction_monitor project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file (if present)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0cvg$*da@$p&gd0pgu=o1+z-2=2x5abtmkk-6=xa97vt_042_@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework.authtoken',
    'oauth2_provider',           # OAuth2 Authorization Server (replaces simplejwt)

    # Argus apps (fraud_engine before transactions so detector is ready when signals run)
    'users',
    'fraud_engine.apps.FraudEngineConfig',
    'transactions',
    'otp_service',
    'analyst_dashboard',
    'frontend_api',
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',  # OAuth2/JWT for frontend
        'rest_framework.authentication.TokenAuthentication',            # Token for customer-app
        # Note: SessionAuthentication removed — it forces CSRF on all API views,
        # which breaks JWT/Token-based frontends that don't send CSRF cookies.
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

# ── OAuth2 / JWT configuration ─────────────────────────────────────────────
OAUTH2_PROVIDER = {
    # Issue signed JWTs (not opaque tokens)
    'ACCESS_TOKEN_GENERATOR':          'argus_transaction_monitor.oauth_jwt.generate_jwt_token',
    'REFRESH_TOKEN_GENERATOR':         'oauth2_provider.generators.generate_client_id',

    'ACCESS_TOKEN_EXPIRE_SECONDS':     8 * 60 * 60,   # 8 hours
    'REFRESH_TOKEN_EXPIRE_SECONDS':    7 * 24 * 60 * 60,  # 7 days
    'ROTATE_REFRESH_TOKEN':            True,

    'SCOPES': {
        'read':    'Read access',
        'write':   'Write access',
        'analyst': 'Analyst role',
        'auditor': 'Auditor role',
    },
    # Allow the ROPC (password) grant
    'ALLOWED_REDIRECT_URI_SCHEMES': ['https', 'http'],
    'OAUTH2_VALIDATOR_CLASS': 'argus_transaction_monitor.oauth_validator.ArgusOAuth2Validator',
}

MIDDLEWARE = [
    'argus_transaction_monitor.cors_middleware.CorsMiddleware',  # CORS for customer-app
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'

# CORS — allow the local customer-app (opened as file:// or localhost) to reach the API
CORS_ALLOWED_ORIGINS = [
    'http://127.0.0.1:5500',
    'http://localhost:5500',
    'http://127.0.0.1:8080',
    'http://localhost:8080',
]
CORS_ALLOW_ALL_ORIGINS_IN_DEBUG = True  # used by our custom middleware

ROOT_URLCONF = 'argus_transaction_monitor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'frontend' / 'templetes'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'argus_transaction_monitor.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'frontend' / 'static',
]

# ── Google OAuth ──────────────────────────────────────────────────────────────
# Reads GOOGLE_CLIENT_ID or GOOGLE_OAUTH_CLIENT_ID from .env — either name works.
# The GIS popup flow only needs the Client ID (no Client Secret).
GOOGLE_OAUTH_CLIENT_ID = (
    os.environ.get('GOOGLE_CLIENT_ID') or
    os.environ.get('GOOGLE_OAUTH_CLIENT_ID', '')
)
