# Generated by Django 6.0.2 on 2026-03-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('CLOSED_RESOLVED', 'Closed – Resolved'), ('CLOSED_FALSE_POSITIVE', 'Closed – False Positive')], default='OPEN', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('resolution', models.TextField(blank=True, default='')),
                ('analyst_name', models.CharField(default='Unassigned', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
