# Generated by Django 6.0.2 on 2026-02-07 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('OTP_REQUIRED', 'OTP Required'), ('BLOCKED', 'Blocked')], default='INITIATED', max_length=20)),
                ('fraud_decision', models.CharField(blank=True, choices=[('ALLOW', 'Allow'), ('CHALLENGE', 'Challenge'), ('DENY', 'Deny')], max_length=20, null=True)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('channel', models.CharField(default='APP', max_length=50)),
                ('otp_required', models.BooleanField(default=False)),
                ('otp_verified', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.user')),
            ],
        ),
    ]
