# Generated by Django 6.0.2 on 2026-02-14 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_city_transaction_payment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='device_id',
            new_name='device_type',
        ),
    ]
