# Generated by Django 4.2.28 on 2026-02-28 04:15

from django.db import migrations, models
import transactions.models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_rename_device_id_to_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='device_type',
            field=models.CharField(blank=True, help_text='e.g. Mobile, Laptop, Tablet', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txn_id',
            field=models.CharField(default=transactions.models.generate_txn_id, max_length=100, unique=True),
        ),
    ]
