# -*- coding: utf-8 -*-
"""ml_rf_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n19ofYlI5xyOqG1SJu1tUJUM0Y3LuQ85
"""

import warnings

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
import joblib
from django.conf import settings
import os
from datetime import timedelta
from sklearn.metrics import classification_report, roc_auc_score
from xgboost import XGBClassifier

MODEL_PATH = os.path.join(settings.BASE_DIR, "ml_assests", "argus_rf_model.joblib")
XGB_MODEL_PATH = os.path.join(settings.BASE_DIR, "ml_assests", "argus_xgb_model.joblib")
ENCODER_PATH = os.path.join(settings.BASE_DIR, "ml_assests", "argus_encoder.joblib")
META_MODEL_PATH = os.path.join(settings.BASE_DIR, "ml_assests", "argus_meta_lr_model.joblib")


class ArgusFraudDetector:

    FEATURE_COLS = [
        'Transaction_Amount', 'Account_Balance', 'Daily_Transaction_Count',
        'Avg_Transaction_Amount_7d', 'Failed_Transaction_Count_7d',
        'Is_Weekend', 'New_Device', 'Device_Type_Enc'
    ]

    def __init__(self):
        self._rf_model = None
        self._xgb_model = None
        self._encoder = None
        self._meta_model = None  # Logistic Regression: final fraud risk score from RF + XGB scores

    # -------------------------
    # LOAD MODELS
    # -------------------------
    def _get_assets(self):
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", UserWarning)
            try:
                from sklearn.exceptions import InconsistentVersionWarning
                warnings.simplefilter("ignore", InconsistentVersionWarning)
            except ImportError:
                pass
            if self._rf_model is None:
                self._rf_model = joblib.load(MODEL_PATH)

            if self._xgb_model is None:
                self._xgb_model = joblib.load(XGB_MODEL_PATH)

            if self._encoder is None:
                self._encoder = joblib.load(ENCODER_PATH)

            if self._meta_model is None and os.path.exists(META_MODEL_PATH):
                self._meta_model = joblib.load(META_MODEL_PATH)

        return self._rf_model, self._xgb_model, self._encoder

    # -------------------------
    # PREPARE DATA
    # -------------------------
    def prepare_training_data(self, df):

        df = df.copy()
        df['Timestamp'] = pd.to_datetime(df['Timestamp'])

        df['Is_Weekend'] = (df['Timestamp'].dt.dayofweek >= 5).astype(int)

        le = LabelEncoder()
        df['Device_Type_Enc'] = le.fit_transform(df['Device_Type'].astype(str))

        joblib.dump(le, ENCODER_PATH)
        self._encoder = le

        if 'New_Device' not in df.columns:
            df['New_Device'] = 0

        X = df[self.FEATURE_COLS]
        y = df['Fraud_Label']

        return X, y

    def evaluate_models(self, rf, xgb, X_test, y_test):

      rf_pred = rf.predict(X_test)
      xgb_pred = xgb.predict(X_test)

      print("\n===== RANDOM FOREST REPORT =====")
      print(classification_report(y_test, rf_pred))
      print("ROC-AUC:", roc_auc_score(y_test, rf.predict_proba(X_test)[:,1]))

      print("\n===== XGBOOST REPORT =====")
      print(classification_report(y_test, xgb_pred))
      print("ROC-AUC:", roc_auc_score(y_test, xgb.predict_proba(X_test)[:,1]))

    # -------------------------
    # TRAIN BOTH MODELS
    # -------------------------
    def train_and_save(self, X, y):

        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, random_state=42
        )

        # Random Forest
        rf = RandomForestClassifier(
            n_estimators=100,
            class_weight='balanced',
            random_state=42
        )
        rf.fit(X_train, y_train)

        print("Random Forest Accuracy:", rf.score(X_test, y_test))
        joblib.dump(rf, MODEL_PATH)
        self._rf_model = rf

        # XGBoost
        xgb = XGBClassifier(
            n_estimators=200,
            learning_rate=0.1,
            max_depth=5,
            scale_pos_weight=5,
            random_state=42,
            use_label_encoder=False,
            eval_metric='logloss'
        )

        xgb.fit(X_train, y_train)

        print("XGBoost Accuracy:", xgb.score(X_test, y_test))
        self.evaluate_models(rf, xgb, X_test, y_test)

        joblib.dump(xgb, XGB_MODEL_PATH)
        self._xgb_model = xgb

        # Meta-model: Logistic Regression on RF + XGB proba (fraud class) -> final fraud risk score
        rf_proba_train = rf.predict_proba(X_train)[:, 1]
        xgb_proba_train = xgb.predict_proba(X_train)[:, 1]
        X_meta = np.column_stack([rf_proba_train, xgb_proba_train])
        meta = LogisticRegression(max_iter=1000, random_state=42, class_weight='balanced')
        meta.fit(X_meta, y_train)
        joblib.dump(meta, META_MODEL_PATH)
        self._meta_model = meta
        meta_proba_test = meta.predict_proba(
            np.column_stack([
                rf.predict_proba(X_test)[:, 1],
                xgb.predict_proba(X_test)[:, 1]
            ])
        )[:, 1]
        print("\n===== META (Logistic Regression) REPORT =====")
        print("ROC-AUC:", roc_auc_score(y_test, meta_proba_test))





    # -------------------------
    # PREDICT
    # -------------------------
    def predict_fraud(self, transaction_data, user_history):

        rf, xgb, le = self._get_assets()
        now = pd.to_datetime(transaction_data.get('Timestamp', pd.Timestamp.now()))

        # Feature Engineering
        if user_history is None or user_history.empty:
            avg_amount_7d = 0
            failed_7d = 0
            txn_count_24h = 0
            new_device_flag = 1
        else:
            history_7d = user_history[
                user_history['Timestamp'] >= (now - timedelta(days=7))
            ]

            history_24h = history_7d[
                history_7d['Timestamp'] >= (now - timedelta(days=1))
            ]

            avg_amount_7d = history_7d['Transaction_Amount'].mean() if not history_7d.empty else 0
            failed_7d = (history_7d['status'] == 'FAILED').sum() if 'status' in history_7d.columns else 0
            txn_count_24h = len(history_24h)

            if 'Device_Type' in user_history.columns:
                known_devices = user_history['Device_Type'].unique()
                new_device_flag = 1 if transaction_data['Device_Type'] not in known_devices else 0
            else:
                new_device_flag = 1

        try:
            device_enc = int(le.transform([str(transaction_data.get('Device_Type', '')).strip() or 'Unknown'])[0])
        except (ValueError, TypeError):
            # Unknown device type: use 0 so model isn't over-penalized (e.g. "Mobile"/"Laptop" not in training)
            device_enc = 0

        feature_dict = {
            'Transaction_Amount': transaction_data.get('Transaction_Amount', 0),
            'Account_Balance': transaction_data.get('Account_Balance', 0),
            'Daily_Transaction_Count': txn_count_24h,
            'Avg_Transaction_Amount_7d': avg_amount_7d,
            'Failed_Transaction_Count_7d': failed_7d,
            'Is_Weekend': int(now.weekday() >= 5),
            'New_Device': int(new_device_flag),
            'Device_Type_Enc': device_enc
        }

        X_pred = pd.DataFrame([feature_dict])[self.FEATURE_COLS]

        rf_score = rf.predict_proba(X_pred)[0][1]
        xgb_score = xgb.predict_proba(X_pred)[0][1]

        # Final fraud risk score: meta-model (Logistic Regression) if available, else fixed blend
        if self._meta_model is not None:
            risk_score = float(
                self._meta_model.predict_proba([[rf_score, xgb_score]])[0][1]
            )
        else:
            risk_score = (0.4 * rf_score) + (0.6 * xgb_score)

        if risk_score < 0.3:
            decision = "ALLOW"
        elif risk_score < 0.7:
            decision = "CHALLENGE"
        else:
            decision = "DENY"

        return float(risk_score), decision


# ==============================
# EXECUTION (only when run as script, not on Django import)
# ==============================

if __name__ == "__main__":
    detector = ArgusFraudDetector()

    if not os.path.exists(MODEL_PATH):
        print("Training models...")
        df_real = pd.read_csv("Fraud_dataset.csv")
        X, y = detector.prepare_training_data(df_real)
        detector.train_and_save(X, y)
    else:
        print("Models already trained.")

    # ==============================
    # TEST CASES
    # ==============================

    print("\n--- Test 1: Low Amount ---")
    txn = {
        "Transaction_Amount": 200,
        "Account_Balance": 5000,
        "Device_Type": "Mobile",
        "Timestamp": pd.Timestamp.now()
    }
    score, decision = detector.predict_fraud(txn, pd.DataFrame())
    print("Risk:", round(score*100,2), "%", "Decision:", decision)

    print("\n--- Test 2: High Amount ---")
    txn["Transaction_Amount"] = 75000
    txn["Account_Balance"] = 80000
    score, decision = detector.predict_fraud(txn, pd.DataFrame())
    print("Risk:", round(score*100,2), "%", "Decision:", decision)

    print("\n--- Test 3: Failed Pattern ---")
    history_failed = pd.DataFrame({
        "Transaction_Amount": [1000]*4,
        "Device_Type": ["Mobile"]*4,
        "Timestamp": [
            pd.Timestamp.now() - timedelta(hours=5),
            pd.Timestamp.now() - timedelta(hours=4),
            pd.Timestamp.now() - timedelta(hours=3),
            pd.Timestamp.now() - timedelta(hours=2)
        ],
        "status": ["FAILED"]*4
    })
    txn["Transaction_Amount"] = 5000
    score, decision = detector.predict_fraud(txn, history_failed)
    print("Risk:", round(score*100,2), "%", "Decision:", decision)

    print("\n--- Test 4: Unseen Device ---")
    txn["Device_Type"] = "SmartTV"
    score, decision = detector.predict_fraud(txn, history_failed)
    print("Risk:", round(score*100,2), "%", "Decision:", decision)

    print("\n--- Test 5: Very Safe Returning User (Expected ALLOW) ---")
    safe_history = pd.DataFrame({
        "Transaction_Amount": [300, 320, 310, 290, 305],
        "Device_Type": ["Mobile"] * 5,
        "Timestamp": [
            pd.Timestamp.now() - timedelta(days=5),
            pd.Timestamp.now() - timedelta(days=4),
            pd.Timestamp.now() - timedelta(days=3),
            pd.Timestamp.now() - timedelta(days=2),
            pd.Timestamp.now() - timedelta(days=1),
        ],
        "status": ["SUCCESS"] * 5
    })
    safe_txn = {
        "Transaction_Amount": 315,
        "Account_Balance": 10000,
        "Device_Type": "Mobile",
        "Timestamp": pd.Timestamp.now()
    }
    score, decision = detector.predict_fraud(safe_txn, safe_history)
    print("Risk:", round(score * 100, 2), "%", "Decision:", decision)