# Generated by Django 4.2.28 on 2026-02-28 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionotp',
            old_name='otp_code',
            new_name='otp',
        ),
        migrations.RemoveField(
            model_name='transactionotp',
            name='attempts',
        ),
    ]
