# Generated by Django 6.0.2 on 2026-03-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_service', '0002_rename_otp_code_transactionotp_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionotp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
