# Generated by Django 6.0.2 on 2026-03-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_service', '0003_alter_transactionotp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionotp',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transactionotp',
            name='secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
