HIGH_AMOUNT_THRESHOLD = 100000
RAPID_TXN_COUNT = 3
RAPID_TXN_WINDOW_MIN = 5
FAILED_ATTEMPTS_LIMIT = 5
FAILED_ATTEMPTS_WINDOW_MIN = 30
DAILY_VELOCITY_LIMIT = 50000
RISKY_PAYMENT_TYPES = ["UPI", "WALLET"]